# Generated by Django 4.1.4 on 2023-02-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('parv', models.IntegerField(choices=[(0, 'ACAP'), (1, 'AMTE'), (2, 'AMBOS')], default=0)),
            ],
        ),
    ]
