# Generated by Django 4.1.4 on 2023-02-09 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField()),
                ('idAbonado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonados.abonado')),
            ],
        ),
    ]
