# Generated by Django 4.1.4 on 2023-02-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paradas', '0001_initial'),
        ('abonados', '0002_abono'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonadoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(choices=[('ACAP', 'A Capital'), ('AMTE', 'A MonteGrande')], default='ACAP', max_length=4)),
                ('dia', models.CharField(choices=[('Do', 'Domingo'), ('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Miércoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes'), ('Sa', 'Sábado')], max_length=2)),
                ('hora', models.TimeField()),
                ('idAbonado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonados.abonado')),
                ('idparada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradas.parada')),
            ],
        ),
    ]
