# Generated by Django 4.1.4 on 2023-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonados', '0003_abonadodia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonadodia',
            name='dia',
            field=models.CharField(choices=[('0Do', 'Domingo'), ('1Lu', 'Lunes'), ('2Ma', 'Martes'), ('3Mi', 'Miércoles'), ('4Ju', 'Jueves'), ('5Vi', 'Viernes'), ('6Sa', 'Sábado')], max_length=3),
        ),
    ]
