# Generated by Django 4.1.4 on 2023-02-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='fecha',
            field=models.DateField(),
        ),
    ]
