# Generated by Django 4.1.4 on 2023-02-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['destino', 'dia', 'hora']},
        ),
    ]
