# Generated by Django 4.1.4 on 2023-02-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0003_alter_tarifa_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='dia',
            field=models.CharField(choices=[('Do', 'Domingo'), ('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Miércoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes'), ('Sa', 'Sábado')], max_length=2),
        ),
    ]
