# Generated by Django 4.1.4 on 2023-03-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0004_alter_tarifa_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='dia',
            field=models.CharField(choices=[('0Do', 'Domingo'), ('1Lu', 'Lunes'), ('2Ma', 'Martes'), ('3Mi', 'Miércoles'), ('4Ju', 'Jueves'), ('5Vi', 'Viernes'), ('6Sa', 'Sábado')], max_length=3),
        ),
    ]
